### ISSUE TITLE
Payload should be max 1MB

### ISSUE THREAD

**Issue by VladaPetrovic** [sraka1/Databox-PHP-SDK#7]
[Here](https://github.com/sraka1/Databox-PHP-SDK/blob/master/src/Databox/DataboxClient.php#L57) you should check if payload is larger then 1MB and split it in separate calls if so.

**Comment by VladaPetrovic** [comment]
@sraka1 when should we expect this to be done?

**Comment by sraka1** [comment]
It's done, I just haven't closed the issue yet.

On Friday, April 4, 2014, Vlada Petrović notifications@github.com wrote:

> @sraka1 https://github.com/sraka1 when should we expect this to be done?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sraka1/Databox-PHP-SDK/issues/7#issuecomment-39556605
> .

## 

Lp,
Jakob
